---
version: 2
plan:
  project-key: WT
  key: GRPCWEB
  name: grpc-web-rx
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  tasks:
    - checkout:
        force-clean-build: 'false'
    - command:
        executable: make
        argument: clean
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/usr/bin/env bash
            set -o errexit ; set -o errtrace ; set -o pipefail
            export NVM_DIR="$HOME/.nvm"
            [[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
            [[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"
            npm ci
            npm pack
  artifacts:
    - name: grpc-web-rx.tgz
      pattern: "*.tgz"
      shared: true
      required: true
triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: WT-GRPCWEB
plan-permissions:
  - groups:
      - bamboo-build-team
    permissions:
      - view
      - edit
      - build
  - groups:
      - bamboo-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
  - roles:
      - logged-in
    permissions:
      - view
...
---
version: 2
deployment:
  name: grpc-web-rx
  source-plan: WT-GRPCWEB
release-naming:
  next-version-name: 3.0.56-1652
  applies-to-branches: false
  auto-increment: true
  auto-increment-variables: []
environments:
  - prod
prod:
  triggers: []
  tasks:
    - clean
    - artifact-download:
        artifacts:
          - { }
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            echo "//registry.npmjs.org/:_authToken=\${bamboo_SECRET_NPM_TOKEN}" > .npmrc
            npm publish grpc-web-rx-*.tgz
  variables:
    SECRET_NPM_TOKEN: BAMSCRT@0@0@tm6a4CR4DfgDWQxKHb+Kv3jvxOCb+NdYoGLjuyH5wIo1Xm+ft/a1vb7ndRvwtRqc
  requirements: []
  notifications: []
---
version: 2
deployment:
  name: grpc-web-rx
deployment-permissions:
  - groups:
      - bamboo-admin
    permissions:
      - view
      - edit
  - roles:
      - logged-in
    permissions:
      - view

environment-permissions:
  - prod:
      - groups:
          - bamboo-deploy-team-prod
        permissions:
          - view
          - deploy
      - groups:
          - bamboo-admin
        permissions:
          - view
          - edit
          - deploy
...
